version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: p3tki
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/p3tki
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/private_key.pem:/app/src/main/resources/private_key.pem
      - ./src/main/resources/public_key.pem:/app/src/main/resources/public_key.pem

volumes:
  postgres_data:
